### ISSUE TITLE
[Bug] Neither command '/bestenliste' nor '/listenbeste' working proberly... Please Fix!

### ISSUE THREAD

**Issue by lukaslustmolch** [skillor/Spark#24]
**Describe the bug**
A clear and concise description of what the bug is:
Feature not working. 
Read following:

**To Reproduce**
1. Go to a server that uses this discord bot
2. Click on a channel
3. Scroll down to end

**Expected behavior**
Typing '/bestenliste' or '/listenbeste' working.

**Actual behavior**
Typing '/bestenliste' or '/listenbeste' not working.

**Screenshots**
![Unbenaaaannt](https://user-images.githubusercontent.com/37021525/123523916-518d9000-d6c7-11eb-8812-b2212cd2c50a.png)

**Setup (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, ...] required
 - Discord Application required
 - Keyboard required for command or use copy and paste -> then mouse required

**Comment by dreiekk** [comment]
+1

**Comment by skillor** [comment]
Internationalization is not supported

**Comment by dreiekk** [comment]
> 
> 
> Internationalization is not supported

(yet)
