### ISSUE TITLE
doubled message reactions not solely removable

### ISSUE THREAD

**Issue by KGS501** [skillor/Spark#32]
**Information about the bug**

The bot allows you to assign two different actions to a single message-reaction emoji but does not let you remove one of them without removing the other.

**To Reproduce**
1. Assign a message-reaction
e.g. `/mreact add {message-id} {emoji} toggle-role {role-id}`
2. Assign a second meassage-reaction but to the same emoji with a different action
e.g. `/mreact add {same message-id} {same emoji} dm {message}`
3. Now to remove **only one** of the two actions assigned to the same emoji
4. The Bot is only able to distinguish between different emojis, so will delete both of your actions

**Expected behavior**

The `/mreact remove` should be able to differantiate between multiple actions assigned to the same emoji

**Comment by skillor** [comment]
It was not an intended feature to have multiple actions to one emoji so I have to further investigate this behaviour. I will also improve the deletion of message reactions.
